name: trifusesurv2-2.1.3
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - setuptools>=68
  - wheel
  - einops
  - monai
  - numpy
  - pandas
  - pydicom
  - simpleitk
  - scikit-learn
  - matplotlib
  - pytorch=2.5.1=*cuda12.4*
  - pytorch-cuda=12.4
